OnlineBedBookingSystem/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from home.views import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hospital/', include('hospital.urls', namespace='hospital')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('userapp/', include('userapp.urls', namespace='userapp')),
    path('bookpatient/', include('bookpatient.urls', namespace='bookpatient')),
    path('accounts/', include('allauth.urls')),
    path('', IndexView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path

from .views import *
from .api import *


app_name = 'customer'


urlpatterns = [
    # path for view
    path('login', CustomerLoginView.as_view(), name='customer_login'),
    path('registration', CustomerRegistrationView.as_view(), name='customer_registration'),
    path('dashboard', CustomerDashboardView.as_view(), name='customer_dashboard'),

    # path for api
    path('create-new-customer/', CustomerRegisterAPI.as_view(), name='create_new_customer'),
    path('customer-login/', CustomerLoginAPI.as_view(), name='customer_login_api'),
    path('customer-logout', CustomerLogoutAPIView.as_view(), name='customer_logout'),
    path('update-patient-info/', UpdatePatientDetailAPI.as_view(), name='update_patient_info'),
    path('add-temp-patient/', TempAddPatientAPI.as_view(), name='add_patient_temp'),
    path('search-hospitals', HospitalSearchAPI.as_view(), name='search_hospitals'),
]

userapp/urls.py
from django.urls import path
from userapp.api import *

app_name = 'userapp'

urlpatterns = [
    path('get-user-details', UserDetailsAPIView.as_view(), name='user_details'),
]

customer/models.py
from django.db import models
from django.utils import timezone
from django.dispatch import receiver
from django.db.models.signals import pre_save

from OnlineBedBookingSystem.custom import *
from userapp.models import Account
from hospital.models import Hospital


class Patient(models.Model):

    reference_user                  = models.ForeignKey(Account, verbose_name=("reference user"), on_delete=models.SET_NULL, null=True)
    hospital                        = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    name                            = models.CharField(max_length=255, verbose_name='patient name')
    slug                            = models.SlugField(blank=True, null=True)
    GENDER_CHOICE                   = (
                                            ('male', 'Male'),
                                            ('female', 'Female')
                                        )
    gender                          = models.CharField(max_length=7, choices=GENDER_CHOICE, default='male')
    p_mobile                        = models.CharField(max_length=12, verbose_name='Primary mobile')
    s_mobile                        = models.CharField(max_length=12, verbose_name='Secondary mobile', blank=True, null=True)
    STATUS_CHOICE                   = (
                                            ('Alive', 'Alive'),
                                            ('Success', 'Success'),
                                            ('Dead', 'Dead')
                                        )
    status                          = models.CharField(max_length=20, choices=STATUS_CHOICE, default='Alive')
    adhar                           = models.CharField(max_length=50, unique=True)
    dob                             = models.DateField()
    BED_CHOICE                      = (
                                            ('word', 'Word'),
                                            ('icu', 'ICU')
                                        )
    bed                             = models.CharField(max_length=20, choices=BED_CHOICE, default='Word')
    created_at                      = models.DateTimeField(default=timezone.now)
    update_at                       = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
    def patient_status(self):
        return self.status

    class Meta:
        verbose_name = 'Patient'
        verbose_name_plural = 'Patients'
        ordering = ['-created_at',]

@receiver(pre_save, sender=Patient)
def _pre_save_receiver(sender, instance, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator_through_name(instance)

customer/views.py
from django.shortcuts import render, redirect
from django.views import View

from hospital.models import Hospital
from bookpatient.models import Notification


def logged_in(request):
    user = request.user

    if user.is_authenticated == True and user.admin == False and user.is_customer == True and user.is_authority == False:
        return True
    else:
        return False


class CustomerLoginView(View):
    template_name = 'customer/customer-login-registration.html'

    def get(self, request):
        if logged_in(request):
            return redirect('customer:customer_dashboard')
        else:    
            return render(request, self.template_name, {'title': 'Customer Sign in'})


class CustomerRegistrationView(View):
    template_name = 'customer/customer-login-registration.html'

    def get(self, request):
        return render(request, self.template_name, {'class': 'right-panel-active', 'title': 'Customer Sign up'})


class CustomerDashboardView(View):
    template_name = 'customer/customer-dashboard.html'

    def get(self, request):
        if logged_in(request):
            return render(request, self.template_name)
        else:
            return redirect('customer:customer_login')

customer/templates/customer/customer-dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title id="page_title">&nbsp;</title>
        <link href="{% static 'vendor/css/styles.css' %}" rel="stylesheet" />
        <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
        <!-- link static css -->
        <link href="{% static 'resources/css/customer-dashboard.css' %}" rel="stylesheet" />

        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body class="sb-nav-fixed">
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <a class="navbar-brand" href="index.html" id="profile_name"></a>
            <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
            <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
                <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" id="search-field" />
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="button"  data-toggle="modal" data-target="#myModal" onclick="search_hospitals()"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </form>
            <!-- Navbar-->
            <ul class="navbar-nav ml-auto ml-md-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="https://i.postimg.cc/BbKp2Y9K/user.png" height="25" width="25" id="profile_name" /></a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                        <a class="dropdown-item" href="#">Your Profile</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'customer:customer_logout' %}">Logout</a>
                    </div>
                </li>
            </ul>
        </nav>

          <!-- Modal -->
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <!-- <h4 class="modal-title">Modal Header</h4> -->
                    </div>
                    <div class="modal-body" id="model-id">
                        <div class="content">
                            <p id="name-id"><a href="">&nbsp;</a></p>
                            <p id="address-id">&nbsp;</p>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

    <!-- Modal -->
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" href="{% url 'index' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-home"></i></div>
                                Home
                            </a>
                        </div>
                    </div>
                    <div class="sb-sidenav-footer" id="profile_name_footer">
                        
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                <main>
                    <div class="container-fluid">
                        <h1 class="mt-4">Dashboard</h1>
                        <ol class="breadcrumb mb-4">
                            <li class="breadcrumb-item active">Dashboard</li>
                        </ol>

                        <div class="alert alert-success" role="alert">
                            A simple success alert—check it out!
                        </div>

                        <div class="row">
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-primary text-white mb-4" style="cursor: pointer;">
                                    <div class="card-body">Total covid cases</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" onclick="get_patients('All')">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-warning text-white mb-4" style="cursor: pointer;">
                                    <div class="card-body">Current covid cases</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" onclick="get_patients('Alive')">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-success text-white mb-4" style="cursor: pointer;">
                                    <div class="card-body">Success covid cases</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" onclick="get_patients('Success')">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-danger text-white mb-4" style="cursor: pointer;">
                                    <div class="card-body">Death covid cases</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" onclick="get_patients('Dead')">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="card mb-4">
                            <div class="card-header" id="databse_name">
                                <i class="fas fa-table mr-1"></i>
                                &nbsp;
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th>Name</th>
                                                <th>Adhar No.</th>
                                                <th>Status</th>
                                                <th>Admit at</th>
                                            </tr>
                                        </thead>
                                        <tfoot>
                                            <tr>
                                                <th>Name</th>
                                                <th>Adhar No.</th>
                                                <th>Status</th>
                                                <th>Admit at</th>
                                            </tr>
                                        </tfoot>
                                        <tbody>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>                   
                    
                </main>
            </div>
        </div>
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'vendor/js/scripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
        <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
        <script src="{% static 'vendor/js/datatables-demo.js' %}"></script>
        <script src="{% static 'resources/js/customer-dashboard.js' %}"></script>
    </body>
</html>

customer/templates/customer/customer-login-registration.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'resources/css/customer-login.css' %}" />
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
    <title>{{title}}</title>
  </head>
  <body>

    <div class="container {{class}}" id="container">
      <div class="form-container sign-up-container">
        <div class="form">
          {% csrf_token %}
          <h1>Sign Up</h1>
          <div class="social-container">
            <a href="/accounts/google/login/?process=login" class="social"><img src="https://i.postimg.cc/zfnhrh7p/google.png" height="20" width="20"></a>
          </div>
          <span>or use your email for registration</span>
          <input type="email" id="reg-email" placeholder="Email" />
          <input type="text" id="reg-username" placeholder="Username" />
          <input type="password" id="reg-password" placeholder="Password" />
          <button id="sign-up-btn-id">Sign Up</button>
          <p class="error-message" id="error-msg">&nbsp;</p>
        </div>
      </div>
      <div class="form-container sign-in-container">
        <div class="form">
          <h1>Sign in</h1>
          <div class="social-container">
            <a href="/accounts/google/login/?process=login" class="social"><img src="https://i.postimg.cc/zfnhrh7p/google.png" height="20" width="20"></a>
          </div>
          <span>or use your account</span>
          <input type="text" placeholder="Username" id="username"/>
          <input type="password" placeholder="Password" id="password" />
          <a href="#">Forgot your password?</a>
          <button onclick="login()">Sign In</button>
          <p class="error-message" id="sign-inerror-msg">&nbsp;</p>
        </div>
      </div>
      <div class="overlay-container">
        <div class="overlay">
          <div class="overlay-panel overlay-left">
            <h1>Welcome Back!</h1>
            <p>To keep connected with us please login with your personal info</p>
            <button class="ghost" id="signIn">Sign In</button>
          </div>
          <div class="overlay-panel overlay-right">
            <h1>Hello, Friend!</h1>
            <p>Enter your personal details and start journey with us</p>
            <button class="ghost" id="signUp">Sign Up</button>
          </div>
        </div>
      </div>
    </div>


    <!-- bootstrap js links -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'resources/js/customer-login.js' %}"></script>
  </body>
</html>

customer/templates/customer/patient-view.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
        <link href="{% static 'resources/css/patient-view.css' %}" rel="stylesheet" />
        <title>&nbsp;</title>
    </head>
    <body>

        {{ patient|json_script:"patient" }}

        {% csrf_token %}

        <div class="my-container" id="form">
            <h2 id="header">Patient Info</h2>
            <div class="form-group row">
                <label for="patient_name" class="col-2 col-form-label">Patient name</label>
                <div class="col-10">
                    <input class="form-control" type="text" value="" id="patient_name" placeholder="Patient name">
                </div>
            </div>

            <div class="form-group row">
                <label for="gender" class="col-2 col-form-label">Gender</label>
                <div class="col-10">
                    <select class="form-control" id="gender">
                        <option selected="true" disabled="disabled">---------</option> 
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                    </select>
                </div>
            </div>

            <div class="form-group row mt-2">
                <label for="p_contact" class="col-2 col-form-label">Primary Contact</label>
                <div class="col-10">
                    <input class="form-control" type="tel" value="" id="p_contact" placeholder="Primary contact no.">
                </div>
            </div>

            <div class="form-group row mt-2">
                <label for="s_contact" class="col-2 col-form-label">Secondary Contact</label>
                <div class="col-10">
                    <input class="form-control" type="tel" value="" id="s_contact" placeholder="Secondary contact no.">
                </div>
            </div>

            <div class="form-group row">
                <label for="status" class="col-2 col-form-label">Patient status</label>
                <div class="col-10">
                    <select class="form-control" id="status">
                        <option selected="true" disabled="disabled">---------</option>
                        <option value="Alive">Alive</option>
                        <option value="Success">Success</option>
                        <option value="Dead">Dead</option>
                    </select>
                </div>
            </div>

            <div class="form-group row">
                <label for="adhar" class="col-2 col-form-label">Adhar no.</label>
                <div class="col-10">
                    <input class="form-control" type="text" value="" id="adhar" placeholder="Patient adhar no.">
                </div>
            </div>

            <div class="form-group row">
                <label for="dob" class="col-2 col-form-label">DOB</label>
                <div class="col-10">
                    <input class="form-control" type="date" value="2011-08-19" id="dob">
                </div>
            </div>

            <div class="form-group row mt-3">
                <label for="bed" class="col-2 col-form-label">Bed type</label>
                <div class="col-10">
                    <select class="form-control" id="bed">
                        <option selected="true" disabled="disabled">---------</option>
                        <option value="word">Word</option>
                        <option value="icu">ICU</option>
                    </select>
                </div>
            </div>
        </div>



        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script src="{% static 'resources/js/patient-view-customer.js' %}"></script>
    </body>
</html>