OnlineBedBookingSystem/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from home.views import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('hospital/', include('hospital.urls', namespace='hospital')),
    path('customer/', include('customer.urls', namespace='customer')),
    path('userapp/', include('userapp.urls', namespace='userapp')),
    path('bookpatient/', include('bookpatient.urls', namespace='bookpatient')),
    path('accounts/', include('allauth.urls')),
    path('', IndexView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path

from .views import *
from .api import *


app_name = 'customer'


urlpatterns = [
    # path for view
    path('login', CustomerLoginView.as_view(), name='customer_login'),
    path('registration', CustomerRegistrationView.as_view(), name='customer_registration'),
    path('dashboard', CustomerDashboardView.as_view(), name='customer_dashboard'),

    # path for api
    path('create-new-customer/', CustomerRegisterAPI.as_view(), name='create_new_customer'),
    path('customer-login/', CustomerLoginAPI.as_view(), name='customer_login_api'),
    path('customer-logout', CustomerLogoutAPIView.as_view(), name='customer_logout'),
    path('update-patient-info/', UpdatePatientDetailAPI.as_view(), name='update_patient_info'),
    path('add-temp-patient/', TempAddPatientAPI.as_view(), name='add_patient_temp'),
    path('search-hospitals', HospitalSearchAPI.as_view(), name='search_hospitals'),
]

hospital/urls.py
from django.urls import path

from .views import *
from .api import *


app_name = 'hospital'


urlpatterns = [
    # path for view
    path('registration', HospitalRegistrationView.as_view(), name='registration'),
    path('authority-login', HospitalLoginView.as_view(), name='login'),
    path('authority-dashboard', HospitalDashboardView.as_view(), name='dashboard'),
    path('<slug:slug>', HospitalDetailView.as_view(), name='hospital_detail'),

    # path for api
    path('register-new-hospital/', CreateHospital.as_view(), name='register_new_hospital'),
    path('login-hospital-authority/', HospitalAuthorityLoginAPI.as_view(), name='authority_login'),
    path('logout/logout-hospital-authority', HospitalAuthorityLogoutAPI.as_view(), name='authority_logout'),
    path('get-patients/<slug:status>', PatientListView.as_view(), name='get_patients'),
    path('update-bed/', UpdateBedAPI.as_view(), name='update_bed'),
    path('get-patient-info/<slug:slug>', PatientDetailView.as_view(), name='patient_details'),
    path('bed-details/<slug:slug>', HospitalBedDetalAPI.as_view(), name='bed_details'),
    path('add-patient/', AddPatientAPI.as_view(), name='add_patient'),
]

userapp/urls.py
from django.urls import path
from userapp.api import *

app_name = 'userapp'

urlpatterns = [
    path('get-user-details', UserDetailsAPIView.as_view(), name='user_details'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views import View


class IndexView(View):

    template_name = 'home/index.html'

    def get(self, request):
        return render(request, self.template_name)

home/templates/home/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>BookYourBed | Home</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'vendor/css/home-styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">BookYourBed</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto my-2 my-lg-0">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'customer:customer_registration' %}">Register User</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'hospital:registration' %}">Register Hospital</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead">
            <div class="container h-100">
                <div class="row h-100 align-items-center justify-content-center text-center">
                    <div class="col-lg-10 align-self-end">
                        <h1 class="text-uppercase text-white font-weight-bold">Book a bed, save a life </h1>
                        <hr class="divider my-4" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <!--<p class="text-white-75 font-weight-light mb-5">Start Bootstrap can help you build better websites using the Bootstrap framework! Just download a theme and start customizing, no strings attached!</p>-->
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="#start">Get started!</a>
                    </div>
                </div>
            </div>
        </header>
        
        <!-- Hospital authority register -->
        <section class="page-section bg-primary" id="start">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8 text-center">
                        <h2 class="text-white mt-0">Register new hospital</h2>
                        <hr class="divider light my-4" />
                        <p class="text-white-50 mb-4">
                            Register your hospital and fill all the details correctly and update number of beds, So that users can find your hospital in the search list.
                        </p>
                        <a class="btn btn-light btn-xl js-scroll-trigger" href="{% url 'hospital:registration' %}">Register new hospital</a>
                    </div>
                </div>
            </div>
        </section>


        

        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container">
                <div class="small text-center text-muted">
                    Copyright &copy;
                    <!-- This script automatically adds the current year to your website footer-->
                    <!-- (credit: https://updateyourfooter.com/)-->
                    <script>
                        document.write(new Date().getFullYear());
                    </script>
                    - BookYourBed
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'vendor/js/home-scripts.js' %}"></script>
    </body>
</html>